# config.yml

backend:
  name: github
  repo: CyberPotat42/cyberpotato-site
  branch: main
media_folder: 'assets/uploads'

collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss ZZ"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Pin", name: "pin", widget: "boolean", default: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Table of Contents", name: "toc", widget: "boolean", default: true}
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - {label: "Math", name: "math", widget: "boolean", default: false}
      - {label: "Mermaid", name: "mermaid", widget: "boolean", default: false}
  # other collections:
  # https://www.netlifycms.org/docs/collection-types/